package com.glycemicgpt.medtronicspike;

/**
 * OpenMinimed SAKE test vectors, shared by the runnable harness and its tests.
 *
 * <p>Two independent fixtures, both reproduced verbatim from OpenMinimed:
 *
 * <ul>
 *   <li>The <b>captured 780G pairing trace</b> ({@link #PUMP_KEYDB_HEX} + {@link #MESSAGES}), from
 *       {@code pysake/constants.py} / {@code SakeServerTest} -- a real recorded pump pairing.
 *   <li>A <b>matched synthetic key-database pair</b> ({@link #CUSTOM_SERVER_KEYDB_HEX} + {@link
 *       #CUSTOM_CLIENT_KEYDB_HEX}), from {@code SakeClientTest} -- generated by the reference
 *       {@code test_key_db_gen.py} so that both sides' permit checks succeed. This is the smallest
 *       configuration that drives a full two-sided handshake; the firmware-extracted databases
 *       cannot be self-paired because their permit payloads are built for a specific real peer.
 * </ul>
 *
 * <p>All values here are <b>shared SAKE protocol constants</b> (firmware-extracted or synthetic
 * test keys), not session secrets and not unique per device. They already ship publicly in
 * OpenMinimed's GPL-3.0 repository. See README.md "Static key DB posture".
 */
public final class SakeTestVectors {

    /** Insulin-pump key database recovered from real 780G firmware (OpenMinimed, public). */
    public static final String PUMP_KEYDB_HEX =
            "f75995e70401011bc1bf7cbf36fa1e2367d795ff09211903da6afbe986b650f1"
                    + "4179c0e6852e0ce393781078ffc6f51919e2eaefbde69b8eca21e41ab59b881a"
                    + "0bea0286ea91dc7582a86a714e1737f558f0d66dc1895c";

    /**
     * Pad byte the phone used for msg4 in the original capture, recovered from the keystream. Only
     * needed to reproduce msg4 byte-for-byte; the handshake completes regardless of its value.
     */
    public static final byte CAPTURED_MSG4_PAD = (byte) 0xf7;

    /** The six 20-byte handshake messages, in wire order, from a real 780G pairing capture. */
    public static final byte[][] MESSAGES =
            new byte[][] {
                decodeHex("0401e2f09017a98f9f01cc56492fbacd4576e92b"), // msg0 server -> pump
                decodeHex("42060e9f344e9312016ee8854d357f659b6b00ba"), // msg1 pump -> server
                decodeHex("fdeeb13d04c3f18d272630ebeabe7c3a4d4d27b9"), // msg2 server -> pump
                decodeHex("c02cec4ffb99affcb553a10fa6c55bb13d9fbacf"), // msg3 pump -> server
                decodeHex("157d8e90214418a0e3d5f0517eebf4a82e00c02e"), // msg4 server -> pump
                decodeHex("9b36f393b296fa84a757809859fc84a5c300d59b"), // msg5 pump -> server
            };

    /** Server-side (MOBILE_APPLICATION) half of the matched synthetic two-sided test pair. */
    public static final String CUSTOM_SERVER_KEYDB_HEX =
            "b079cdc504010144455249564154494f4e5f5f5f4b4559484e4453484b455f41"
                    + "5554485f4b455950484f4e455f5045524d49545f454e4350484f4e455f5045"
                    + "524d49545f4d4143ad14ad2780437db892d5650567d491b9";

    /** Client-side (INSULIN_PUMP) half of the matched synthetic two-sided test pair. */
    public static final String CUSTOM_CLIENT_KEYDB_HEX =
            "db8c1f2801010444455249564154494f4e5f5f5f4b4559484e4453484b455f41"
                    + "5554485f4b455950554d505f5045524d49545f454e435250554d505f504552"
                    + "4d49545f434d4143f2f8dbbb51563d4fa98fdaff0042a432";

    private SakeTestVectors() {}

    /** Decode an even-length hex string to bytes. */
    public static byte[] decodeHex(String hex) {
        if ((hex.length() & 1) != 0) {
            throw new IllegalArgumentException("Hex string has odd length");
        }
        byte[] out = new byte[hex.length() / 2];
        for (int i = 0; i < out.length; i++) {
            int high = Character.digit(hex.charAt(2 * i), 16);
            int low = Character.digit(hex.charAt(2 * i + 1), 16);
            if (high < 0 || low < 0) {
                throw new IllegalArgumentException("Invalid hex character");
            }
            out[i] = (byte) ((high << 4) | low);
        }
        return out;
    }

    /** Encode bytes to a lowercase hex string. */
    public static String toHex(byte[] data) {
        StringBuilder sb = new StringBuilder(data.length * 2);
        for (byte b : data) {
            sb.append(String.format("%02x", b & 0xFF));
        }
        return sb.toString();
    }
}
