/*
 * Vendored from OpenMinimed JavaSake (https://github.com/OpenMinimed/JavaSake)
 * at commit 00c08ae -- verbatim except for this header (verified byte-identical).
 *
 * Copyright (C) OpenMinimed contributors: palmarci (Pal Marci), drfubar,
 * Morten Fyhn Amundsen, Stenium. Original medtronic-bt-decrypt PoC by @planiitis.
 * Android/JVM port maintained by jlengelbrecht.
 *
 * This file is part of GlycemicGPT and is redistributed under the GNU General
 * Public License v3.0, the license under which OpenMinimed makes it available
 * and under which GlycemicGPT itself is released. Used with the author's
 * permission. See tools/medtronic-ble-spike/LICENSE and README.md.
 *
 * Only this attribution header was added; the file is otherwise byte-identical to
 * the pinned upstream commit (applies to vendored main sources and tests alike).
 * Re-vendor from upstream rather than editing here if it drifts.
 */

package org.openminimed.sake;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * End-to-end tests for {@link SakeClient}: driving a fresh client against a fresh server using a
 * matched pair of custom key databases generated by {@code test_key_db_gen.py} in the reference
 * Python implementation.
 *
 * <p>The two databases share the same derivation key, handshake auth key and permit key set;
 * together they form a complete two-sided test pair, the smallest configuration that lets both
 * permit checks succeed.
 */
public class SakeClientTest {

    private static final String KEYDB_CUSTOM_SERVER_HEX =
            "b079cdc504010144455249564154494f4e5f5f5f4b4559484e4453484b455f41"
                    + "5554485f4b455950484f4e455f5045524d49545f454e4350484f4e455f5045"
                    + "524d49545f4d4143ad14ad2780437db892d5650567d491b9";

    private static final String KEYDB_CUSTOM_CLIENT_HEX =
            "db8c1f2801010444455249564154494f4e5f5f5f4b4559484e4453484b455f41"
                    + "5554485f4b455950554d505f5045524d49545f454e435250554d505f504552"
                    + "4d49545f434d4143f2f8dbbb51563d4fa98fdaff0042a432";

    private static KeyDatabase serverKeyDb() {
        return KeyDatabase.fromBytes(Hex.decode(KEYDB_CUSTOM_SERVER_HEX));
    }

    private static KeyDatabase clientKeyDb() {
        return KeyDatabase.fromBytes(Hex.decode(KEYDB_CUSTOM_CLIENT_HEX));
    }

    @Test
    public void clientAndServerCompleteHandshakeAgainstEachOther() throws Exception {
        SakeServer server = new SakeServer(serverKeyDb(), DeviceType.MOBILE_APPLICATION);
        SakeClient client = new SakeClient(clientKeyDb(), DeviceType.INSULIN_PUMP);

        byte[] msg0 = server.handshake(new byte[20]);
        assertNotNull(msg0);
        assertEquals(1, server.getStage());

        byte[] msg1 = client.handshake(msg0);
        assertNotNull(msg1);
        assertEquals(2, client.getStage());

        byte[] msg2 = server.handshake(msg1);
        assertNotNull(msg2);
        assertEquals(3, server.getStage());

        byte[] msg3 = client.handshake(msg2);
        assertNotNull(msg3);
        assertEquals(4, client.getStage());

        byte[] msg4 = server.handshake(msg3);
        assertNotNull(msg4);
        assertEquals(5, server.getStage());

        byte[] msg5 = client.handshake(msg4);
        assertNotNull(msg5);
        assertEquals(6, client.getStage());

        byte[] done = server.handshake(msg5);
        assertEquals(6, server.getStage());
        assertEquals(null, done);
    }

    @Test
    public void handshakeProducesUsableSessionState() throws Exception {
        SakeServer server = new SakeServer(serverKeyDb(), DeviceType.MOBILE_APPLICATION);
        SakeClient client = new SakeClient(clientKeyDb(), DeviceType.INSULIN_PUMP);

        byte[] msg0 = server.handshake(new byte[20]);
        byte[] msg1 = client.handshake(msg0);
        byte[] msg2 = server.handshake(msg1);
        byte[] msg3 = client.handshake(msg2);
        byte[] msg4 = server.handshake(msg3);
        byte[] msg5 = client.handshake(msg4);
        server.handshake(msg5);

        // Both peers must agree on the derived session key.
        assertArrayEquals(
                "client_crypt key must match across peers",
                server.session().clientCrypt().key(),
                client.session().clientCrypt().key()
                );
        assertArrayEquals(
                "server_crypt key must match across peers",
                server.session().serverCrypt().key(),
                client.session().serverCrypt().key()
                );
        assertArrayEquals(
                "session nonce must match across peers",
                server.session().clientCrypt().nonce(),
                client.session().clientCrypt().nonce()
                );

        assertTrue(server.getStage() == 6 && client.getStage() == 6);
    }
}
