/*
 * Vendored from OpenMinimed JavaSake (https://github.com/OpenMinimed/JavaSake)
 * at commit 00c08ae -- verbatim except for this header (verified byte-identical).
 *
 * Copyright (C) OpenMinimed contributors: palmarci (Pal Marci), drfubar,
 * Morten Fyhn Amundsen, Stenium. Original medtronic-bt-decrypt PoC by @planiitis.
 * Android/JVM port maintained by jlengelbrecht.
 *
 * This file is part of GlycemicGPT and is redistributed under the GNU General
 * Public License v3.0, the license under which OpenMinimed makes it available
 * and under which GlycemicGPT itself is released. Used with the author's
 * permission. See tools/medtronic-ble-spike/LICENSE and README.md.
 *
 * Only this attribution header was added; the file is otherwise byte-identical to
 * the pinned upstream commit (applies to vendored main sources and tests alike).
 * Re-vendor from upstream rather than editing here if it drifts.
 */

package org.openminimed.sake;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;

import org.junit.Test;

/**
 * Parity tests against the reference Python implementation ({@code pysake/seqcrypt.py}).
 *
 * <p>The captured ciphertexts below were generated by running the Python SeqCrypt with the same
 * key, nonce and starting sequence values as the test setup here. Any divergence between Java and
 * Python output for the same inputs would cause an assertion to fail.
 */
public class SeqCryptTest {

    private static final byte[] KEY = Hex.decode("00112233445566778899aabbccddeeff");
    private static final byte[] NONCE = Hex.decode("a1b2c3d4e5f60718");

    private static final byte[] PLAIN_0 = Hex.decode("00000000000000000000000000000000ff");
    private static final byte[] PLAIN_1 = Hex.decode("48656c6c6f2c2053414b65212121212121");
    private static final byte[] PLAIN_2 = Hex.decode("deadbeef");

    private static final byte[] CIPHER_SEQ0_0 =
            Hex.decode("7680ea16798357df88b11466330e24d3f200b0e6");
    private static final byte[] CIPHER_SEQ0_1 =
            Hex.decode("9b92fdd551a0cbfc63b5fae41e888ca53c011265");
    private static final byte[] CIPHER_SEQ0_2 = Hex.decode("60c26e3b02e1a3");
    private static final byte[] CIPHER_SEQ1 =
            Hex.decode("28b3469d0ece854f9760df0c7be2e79d93006a3d");

    @Test
    public void encryptMatchesPythonAtSeqZero() {
        SeqCrypt sc = new SeqCrypt(KEY, NONCE, 0L);
        assertArrayEquals(CIPHER_SEQ0_0, sc.encrypt(PLAIN_0));
        assertEquals(2L, sc.getTxSeq());
        assertArrayEquals(CIPHER_SEQ0_1, sc.encrypt(PLAIN_1));
        assertEquals(4L, sc.getTxSeq());
        assertArrayEquals(CIPHER_SEQ0_2, sc.encrypt(PLAIN_2));
        assertEquals(6L, sc.getTxSeq());
    }

    @Test
    public void encryptMatchesPythonAtSeqOne() {
        SeqCrypt sc = new SeqCrypt(KEY, NONCE, 1L);
        assertArrayEquals(CIPHER_SEQ1, sc.encrypt(PLAIN_1));
        assertEquals(3L, sc.getTxSeq());
    }

    @Test
    public void decryptRoundTripsThreeMessages() throws Exception {
        SeqCrypt sc = new SeqCrypt(KEY, NONCE, 0L);
        assertArrayEquals(PLAIN_0, sc.decrypt(CIPHER_SEQ0_0));
        assertEquals(2L, sc.getRxSeq());
        assertArrayEquals(PLAIN_1, sc.decrypt(CIPHER_SEQ0_1));
        assertEquals(4L, sc.getRxSeq());
        assertArrayEquals(PLAIN_2, sc.decrypt(CIPHER_SEQ0_2));
        assertEquals(6L, sc.getRxSeq());
    }

    @Test
    public void decryptRejectsTamperedMac() {
        SeqCrypt sc = new SeqCrypt(KEY, NONCE, 0L);
        byte[] corrupt = CIPHER_SEQ0_0.clone();
        corrupt[corrupt.length - 1] ^= (byte) 0x01;
        assertThrows(MacFailureException.class, () -> sc.decrypt(corrupt));
    }

    @Test
    public void decryptRejectsTamperedCiphertext() {
        SeqCrypt sc = new SeqCrypt(KEY, NONCE, 0L);
        byte[] corrupt = CIPHER_SEQ0_0.clone();
        corrupt[0] ^= (byte) 0x01;
        assertThrows(MacFailureException.class, () -> sc.decrypt(corrupt));
    }

    @Test
    public void encryptDecryptRoundTripIsInverse() throws Exception {
        SeqCrypt tx = new SeqCrypt(KEY, NONCE, 42L);
        SeqCrypt rx = new SeqCrypt(KEY, NONCE, 42L);
        byte[] cipher = tx.encrypt(PLAIN_1);
        byte[] recovered = rx.decrypt(cipher);
        assertArrayEquals(PLAIN_1, recovered);
        assertEquals(tx.getTxSeq(), rx.getRxSeq());
    }

    /**
     * The 1-byte sequence field in the trailer wraps every 256 messages (since it is {@code (seq
     * >>> 1) & 0xFF}). The receiver must reconstruct the full 32-bit sequence using its locally
     * tracked {@code rxSeq} as the base and a delta in [0, 255]. This test exercises the wrap by
     * sending a single message at {@code seq = 512} (trailer byte 0) to a receiver that still
     * tracks {@code rxSeq = 510}.
     */
    @Test
    public void decryptHandlesEightBitSequenceWrap() throws Exception {
        SeqCrypt tx = new SeqCrypt(KEY, NONCE, 512L);
        byte[] cipher = tx.encrypt(PLAIN_1);
        assertEquals(
                "trailer byte should be 0 at seq=512 (wrap-around point)",
                0,
                cipher[cipher.length - 3] & 0xFF
                );

        SeqCrypt rx = new SeqCrypt(KEY, NONCE, 510L);
        byte[] recovered = rx.decrypt(cipher);
        assertArrayEquals(PLAIN_1, recovered);
        assertEquals(514L, rx.getRxSeq());
    }

    /**
     * The receiver must reject incoming sequences that imply a forward jump beyond the configured
     * reorder window. A forged-but-MAC-valid packet at a far-future sequence number could otherwise
     * permanently desync rxSeq.
     */
    @Test
    public void decryptRejectsDeltaBeyondReorderWindow() {
        SeqCrypt tx = new SeqCrypt(KEY, NONCE, 2L * (SeqCrypt.MAX_RX_DELTA + 1));
        byte[] cipher = tx.encrypt(PLAIN_2);
        SeqCrypt rx = new SeqCrypt(KEY, NONCE, 0L);
        assertThrows(MacFailureException.class, () -> rx.decrypt(cipher));
    }

    /**
     * Encrypting past the 2^40 sequence boundary would silently truncate the sequence in the five
     * IV prefix bytes and risk IV reuse. {@link SeqCrypt#encrypt(byte[])} must reject it.
     */
    @Test
    public void encryptRejectsSequenceAtFortyBitBoundary() {
        SeqCrypt sc = new SeqCrypt(KEY, NONCE, SeqCrypt.MAX_SEQ);
        assertThrows(IllegalStateException.class, () -> sc.encrypt(PLAIN_2));
    }
}
